### ISSUE TITLE
why split model to img_model and fusion_model?

### ISSUE THREAD

**Issue by bug-developer021** [Abraham423/CenterFusion#3]
According to https://github.com/HaohaoNJU/CenterFusion/blob/main/tools/CenterFusion/src/convert_onnx.py#L141-L142

**Comment by Hale423** [comment]
There‘re non-NN-based ops between the two engines,  which is not likely to infer as TRT engine, rather,  it's more convenient  to be done by cuda .

**Comment by bug-developer021** [comment]
> There‘re non-NN-based ops between the two engines, which is not likely to infer as TRT engine, rather, it's more convenient to be done by cuda .

got it. thks
