### ISSUE TITLE
why pip install -r requirements.txt, many dependency related with ros pip package could not installed

### ISSUE THREAD

**Issue by ryontang** [Abraham423/CenterFusion#4]
![2023-01-12_13-38](https://user-images.githubusercontent.com/39891618/211987294-3b63bf10-2572-4b30-976d-93dd84eda216.png)

**Comment by Hale423** [comment]
you may simply refers to [this requirements](https://github.com/mrnabati/CenterFusion/blob/master/requirements.txt),
but if you want to visualize the det outputs, you must install ros packages

**Comment by HaohaoNJU** [comment]
solved

**Comment by ryontang** [comment]
> you may simply refers to [this requirements](https://github.com/mrnabati/CenterFusion/blob/master/requirements.txt), but if you want to visualize the det outputs, you must install ros packages

okay, thanks a lot!
