### ISSUE TITLE
复现示例正常，本地数据集可视化结果错误

### ISSUE THREAD

**Issue by ryontang** [Abraham423/CenterFusion#5]
博主您好，感谢您的分享，运行了您的示例代码，效果是正常的，但是当使用本地数据训练的pth->onnx，效果就很不正常，框非常大，debug了一下，发现第二阶段的fusion-onnx是没有问题的，问题有可能出现在图片预处理阶段或者是centernet-onnx文件，看了create_data.py中`def prefetch_test(opt):
                    """
                imgs = data['images'][1.0].numpy() :    1 x 2 x 3 x H_in x W_in, two input image, uint8 dtype
                img = data['image'].numpy().squeeze()    : torch.Size([1, 900, 1600, 3]), one input image , fp32 dtype
                meta = data['meta'] :
                {1.0: {'calib': tensor([[[1.2528e+03, 0.0000e+00, 8.2659e+02, 0.0000e+00],
                             [0.0000e+00, 1.2528e+03, 4.6998e+02, 0.0000e+00],
                             [0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00]]]),
                        'c': tensor([[800., 450.]]),
                        's': tensor([1600.], dtype=torch.float64),
                        'height': tensor([900]),
                        'width': tensor([1600]),
                        'out_height': tensor([112]),
                        'out_width': tensor([200]),
                        'inp_height': tensor([448]),
                        'inp_width': tensor([800]),
                        'trans_input': tensor([[[ 0.5000, -0.0000,    0.0000], [ 0.0000,    0.5000, -1.0000]]], dtype=torch.float64),
                        'trans_output': tensor([[[ 0.1250, -0.0000,    0.0000], [ 0.0000,    0.1250, -0.2500]]], dtype=torch.float64)}}
        
                pc_2d = data['pc_2d']    : 1 x 3 x 1000, point clout dense tensor
                pc_N = data['pc_N']    : 53, valid point num
                pc_dep = data['pc_dep'] : torch.Size([1, 3, 112, 200]),    radar points    in    sparse image shape
                pc_3d = data['pc_3d'] : 1 x 18 x 1000, point cloud dense tensor , why 18 channels ? 
                """
`
我们的图片尺寸是[1280*720],这块我们后续预处理为[1280*768]，想请教下, 看看您这边有没有什么排查错误的思路。

**Comment by Hale423** [comment]
如果你的模型是用自己的数据集训练的，请在[这里](https://github.com/HaohaoNJU/CenterFusion/blob/main/include/config.h) 更改下图片大小的配置，因为这些配置是按照nuscenes数据写的。

**Comment by ryontang** [comment]
> 如果你的模型是用自己的数据集训练的，请在[这里](https://github.com/HaohaoNJU/CenterFusion/blob/main/include/config.h) 更改下图片大小的配置，因为这些配置是按照nuscenes数据写的。

好的，谢谢，排查到是create_data.py的类别设置与模型训练的类别不统一，导致的输出结果错误

**Comment by stanny880913** [comment]
> > 如果你的模型是用自己的数据集训练的，请在[这里](https://github.com/HaohaoNJU/CenterFusion/blob/main/include/config.h) 更改下图片大小的配置，因为这些配置是按照nuscenes数据写的。
> 
> 好的，谢谢，排查到是create_data.py的类别设置与模型训练的类别不统一，导致的输出结果错误

您好，想請問能否詢問您如何用自己的dataset訓練centerfusion呢？謝謝

**Comment by UmangBDhanani** [comment]
> 
Yes I woud also like to know the same, to train centerfusion on own datasets. Thank you in advance.

**Comment by ryontang** [comment]
> > > 如果你的模型是用自己的数据集训练的，请在[这里](https://github.com/HaohaoNJU/CenterFusion/blob/main/include/config.h) 更改下图片大小的配置，因为这些配置是按照nuscenes数据写的。
> > 
> > 
> > 好的，谢谢，排查到是create_data.py的类别设置与模型训练的类别不统一，导致的输出结果错误
> 
> 您好，想請問能否詢問您如何用自己的dataset訓練centerfusion呢？謝謝

您好，参考centerNet和centerFusion的训练过程
1. 首先你需要将本地数据集的格式按照coco数据集整理，具体可以参考convert_nuScenes.py
训练得到一个centerNet pth权重文件，可以把这个baseline作为centerfusion训练的baseline；

(具体可参考centerFusion的 train.sh文件，)
2. 然后冻结baseline的backbone使用centerfusion代码训练目标速度(此时还没有加载radar point)；

3.加载radar point训目标速度/depth/nuscenes_att等属性
